# Generated by Django 3.1.5 on 2021-01-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epizoda',
            name='titulek_cz',
        ),
        migrations.RemoveField(
            model_name='epizoda',
            name='titulek_en',
        ),
        migrations.RemoveField(
            model_name='epizoda',
            name='titulek_sk',
        ),
    ]
