# Generated by Django 3.1.5 on 2021-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20210116_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='url1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url2',
            field=models.CharField(default='', max_length=400),
        ),
    ]
