# Generated by Django 3.1.5 on 2021-01-16 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_auto_20210116_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epizoda',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='popis_epizody',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1_cc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2_cc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3_cc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='delka',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='end_yr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='popis',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='start_yr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url1',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url2',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='zaner',
            field=models.ManyToManyField(null=True, to='serials.Zaner'),
        ),
    ]
