# Generated by Django 3.1.5 on 2021-01-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_auto_20210116_1500'),
    ]

    operations = [
    ]
