# Generated by Django 3.1.5 on 2021-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_auto_20210116_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='vyhledavaci_pole',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
