# Generated by Django 3.1.5 on 2021-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0006_serial_vyhledavaci_pole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epizoda',
            name='popis_epizody',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1_cc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2_cc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3_cc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='end_yr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title_sk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url1',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url2',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='zaner',
            field=models.ManyToManyField(blank=True, to='serials.Zaner'),
        ),
    ]
