# Generated by Django 3.1.5 on 2021-01-20 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0007_auto_20210117_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epizoda',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Čas nahrání'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='1. Embed link'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url1_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nic = 0,titulky = 1, dabing = 2'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='2. Embed link'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url2_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nic = 0,titulky = 1, dabing = 2'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3',
            field=models.TextField(blank=True, default='', null=True, verbose_name='3. Embed link'),
        ),
        migrations.AlterField(
            model_name='epizoda',
            name='url3_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='nic = 0,titulky = 1, dabing = 2'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='vyhledavaci_pole',
            field=models.CharField(max_length=300, null=True, verbose_name='Pole pro vyhledavani(bez diakritiky, vsehny nazvy oddelene ";")'),
        ),
    ]
